// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1645439984);
user_pref("app.update.lastUpdateTime.region-update-timer", 1645440224);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1645439743);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1645439864);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1645439773);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1645440104);
user_pref("browser.cache.disk.amount_written", 0);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.region.update.updated", 1645439717);
user_pref("browser.search.region", "SO");
user_pref("browser.theme.dark-toolbar-theme", true);
user_pref("calendar.timezone.local", "Africa/Mogadishu");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1645439725000");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.cache.lastUpdate", 1645439985);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20220106182030");
user_pref("extensions.lastAppVersion", "91.5.0");
user_pref("extensions.lastPlatformVersion", "91.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"df7202d9-a682-4d15-a32e-b71334bd40fc\",\"google@search.mozilla.org\":\"8f0964ac-0331-4a86-8b15-229919d80559\",\"ddg@search.mozilla.org\":\"6f58d62b-410f-4d2f-b54a-f4d40c3fbbb2\",\"amazondotcom@search.mozilla.org\":\"9abae68d-d25a-489b-b554-b005c186d96e\",\"wikipedia@search.mozilla.org\":\"29880ce2-25fe-4d62-93b0-9db6a1b4cadb\",\"bing@search.mozilla.org\":\"06937a0c-1e4f-439c-b399-622c719d03b0\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 30);
user_pref("mailnews.database.global.datastore.id", "68183f0f-c713-4e70-a7b4-88c556bd729");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "91.5.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("security.sandbox.plugin.tempDirSuffix", "62697a5e-46ed-43bc-9aa0-e9b797eb72c3");
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1626756455894\"");
user_pref("services.settings.last_update_seconds", 1645439864);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1645439864);
user_pref("services.settings.thunderbird.search-config.last_check", 1645439864);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1645439864);
user_pref("toolkit.telemetry.cachedClientID", "7999876b-34e4-4bca-a376-4b7cba20259d");
user_pref("toolkit.telemetry.previousBuildID", "20220106182030");
